language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7

gemfile:
  - Gemfile
  - gemfiles/Gemfile.activemodel-4.0

matrix:
  exclude:
  - rvm: 1.8.7
    gemfile: gemfiles/Gemfile.activemodel-4.0
  - rvm: 1.9.2
    gemfile: gemfiles/Gemfile.activemodel-4.0

script: "echo 'COME ON!' && bundle exec rake spec"
